In [1]:
import hoomd
import numpy
import hoomd.md
import sys
import gsd
import gsd.hoomd
hoomd.context.initialize("/home/themotivation/Avo_atoms/airHCN.gsd")

HOOMD-blue 2.3.3 DOUBLE HPMC_MIXED TBB SSE SSE2 
Compiled: 07/04/2018
Copyright 2009-2018 The Regents of the University of Michigan.
-----
You are using HOOMD-blue. Please cite the following:
* J A Anderson, C D Lorenz, and A Travesset. "General purpose molecular dynamics
  simulations fully implemented on graphics processing units", Journal of
  Computational Physics 227 (2008) 5342--5359
* J Glaser, T D Nguyen, J A Anderson, P Liu, F Spiga, J A Millan, D C Morse, and
  S C Glotzer. "Strong scaling of general-purpose molecular dynamics simulations
  on GPUs", Computer Physics Communications 192 (2015) 97--107
-----
HOOMD-blue is running on the CPU


In [13]:
import mbuild as mb
box = mb.load("/home/themotivation/Avo_atoms/airHCN.pdb")
box.save("/home/themotivation/Avo_atoms/airHCN.gsd")
print("it worked!")

it worked!


/home/themotivation/anaconda3/lib/python3.5/site-packages/mbuild/compound.py:1768: UserWarning: Guessing that "<AR pos=( 0.5265, 0.2604,-1.3727), 0 bonds, id: 139930247124360>" is element: "Ar"
  warn('Guessing that "{}" is element: "{}"'.format(atom, element))


In [2]:
system = hoomd.init.read_gsd("/home/themotivation/Avo_atoms/airHCN.gsd")

notice(2): Group "all" created containing 19904 particles


In [3]:
nl = hoomd.md.nlist.cell();

In [4]:
lj = hoomd.md.pair.lj(r_cut=2.5, nlist=nl);

In [5]:
lj.pair_coeff.set('N','N', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','0', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','AR', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','H', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','C', epsilon=1.0, sigma=1.0);

lj.pair_coeff.set('O','O', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('O','AR', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('O','C', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('O','H', epsilon=1.0, sigma=1.0);

lj.pair_coeff.set('AR','AR', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('AR','H', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('AR','N', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('AR','C', epsilon=1.0, sigma=1.0);

lj.pair_coeff.set('H','C', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('H','H', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('C','N', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('C','C', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','O', epsilon=1.0, sigma=1.0);

In [15]:
fene = hoomd.md.bond.fene()
fene.bond_coeff.set('NN', k=30.0, r0=1.5, sigma=1.0, epsilon= 2.0)
fene.bond_coeff.set('O2', k=30.0, r0=1.0, sigma=1.0, epsilon= 2.0)
fene.bond_coeff.set('HCN', k=30.0, r0=1.0, sigma=1.0, epsilon= 2.0)

**ERROR**: No bonds are defined.


RuntimeError: Error creating bond forces

In [6]:
all = hoomd.group.all();

In [7]:
hoomd.md.integrate.mode_standard(dt=.1)

#hoomd.md.integrate.npt(group=all, kT=2, tau=138, tauP=1, P=2.0) 

integrator = hoomd.md.integrate.npt(group=all, kT=2.49433795843, tau=138.08, tauP=1.0, P=2.0) # if comment out this line then NaN error

integrator.randomize_velocities(seed=42)

In [8]:
#hoomd.md.integrate.npt(all, kT=2.49433795843, tau=138.08, S=None, P=2.0, tauP=1, couple='xyz', x=True, y=True, z=True, xy=False, xz=False, yz=False, all=False, nph=False, rescale_all=None, gamma=None)

In [9]:
#hoomd.dump.gsd(filename="trajairHCN.gsd", period=100, group=all, overwrite=True, truncate=False, dynamic=['momentum']);

In [10]:
hoomd.run(1e4);

notice(2): -- Neighborlist exclusion statistics -- :
notice(2): Particles with 0 exclusions             : 19904
notice(2): Neighbors included by diameter          : no
notice(2): Neighbors excluded when in the same body: no
** starting run **


**ERROR**: Particle with unique tag 19903 is no longer in the simulation box.

**ERROR**: Cartesian coordinates: 
**ERROR**: x: -47.0166 y: 372.496 z: 49.5138
**ERROR**: Fractional coordinates: 
**ERROR**: f.x: 0.108876 f.y: 3.59874 f.z: 0.911902
**ERROR**: Local box lo: (-60.1045, -60.1045, -60.1038)
**ERROR**:           hi: (60.1045, 60.1045, 60.1038)


RuntimeError: Error computing cell list

In [11]:
snapshot = system.take_snapshot(particles=True, bonds=True, pairs=False, integrators=True, all=True, dtype='float')

In [12]:
print(snapshot.particles.velocity)

[[ 6.67748392e-01  1.23862766e-01 -3.26953530e-01]
 [-3.46946210e-01 -6.97122514e-01  4.21794914e-02]
 [-4.05285239e-01  1.53828785e-01  3.84475701e-02]
 ...
 [ 1.46844101e+02 -3.61549561e+02 -6.98032074e+01]
 [ 3.71503234e-01 -4.10711825e-01 -2.38035880e-02]
 [-1.74952014e+03  4.30724805e+03  8.32609436e+02]]


In [13]:
box.save("/home/themotivation/Avo_atoms/trajairHCN.gsd")
print("it worked!")

NameError: name 'box' is not defined

In [ ]:
hoomd.data.gsd_snapshot("/home/themotivation/Avo_atoms/trajairHCN.gsd", frame=0)


In [ ]:
print(snap.particles.velocity)
print(hoomd.get_step())

In [ ]:
snap2 = hoomd.data.make_snapshot(N=19904, box=hoomd.data.boxdim(L=100), particle_types=['AR', 'C', 'H', 'N', 'O'])
for x in range(0, 19904):
    snap3.particles.velocity[x] = "trajairHCN.gsd".particles.velocity[x]